export const DB_IMITATE = [
  {
    id: 1,
    name: "The Shawshank Redemption",
    description: "Two imprisoned men bond over a number of years.",
    year: 1994,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    videoUrl: "https://www.youtube.com/watch?v=6hB3S9bIaco",
  },
  {
    id: 2,
    name: "The Godfather",
    description: "The aging patriarch of an organized crime dynasty transfers control to his son.",
    year: 1972,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    videoUrl: "https://www.youtube.com/watch?v=sY1S34973zA",
  },
  {
    id: 3,
    name: "The Dark Knight",
    description: "Batman faces the Joker, a criminal mastermind.",
    year: 2008,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    videoUrl: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
  },
  {
    id: 4,
    name: "Forrest Gump",
    description: "Life journey of a kind-hearted man witnessing historic events.",
    year: 1994,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    videoUrl: "https://www.youtube.com/watch?v=bLvqoHBptjg",
  },
  {
    id: 5,
    name: "Inception",
    description: "A thief steals secrets through dream-sharing technology.",
    year: 2010,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
    videoUrl: "https://www.youtube.com/watch?v=YoHD9XEInc0",
  },
  {
    id: 6,
    name: "Fight Club",
    description: "An underground fight club evolves into something much more.",
    year: 1999,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
    videoUrl: "https://www.youtube.com/watch?v=SUXWAEX2jlg",
  },
  {
    id: 7,
    name: "Interstellar",
    description: "Explorers travel through a wormhole in space to save humanity.",
    year: 2014,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    videoUrl: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
  },
  {
    id: 8,
    name: "The Matrix",
    description: "A hacker learns the truth about reality.",
    year: 1999,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    videoUrl: "https://www.youtube.com/watch?v=vKQi3bBA1y8",
  },
  {
    id: 9,
    name: "Gladiator",
    description: "A Roman general seeks revenge.",
    year: 2000,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    videoUrl: "https://www.youtube.com/watch?v=owK1qxDselE",
  },
  {
    id: 10,
    name: "The Green Mile",
    description: "Supernatural events on death row.",
    year: 1999,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
    videoUrl: "https://www.youtube.com/watch?v=Ki4haFrqSrw",
  },
  {
    id: 11,
    name: "Se7en",
    description: "Detectives hunt a serial killer using the seven deadly sins.",
    year: 1995,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/69Sns8WoET6CfaYlIkHbla4l7nC.jpg",
    videoUrl: "https://www.youtube.com/watch?v=znmZoVkCjpI",
  },
  {
    id: 12,
    name: "Saving Private Ryan",
    description: "A mission to save one soldier during WWII.",
    year: 1998,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg",
    videoUrl: "https://www.youtube.com/watch?v=9CiW_DgxCnQ",
  },
  {
    id: 13,
    name: "The Prestige",
    description: "Two rival magicians battle for supremacy.",
    year: 2006,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w600_and_h900_face/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg",
    videoUrl: "https://www.youtube.com/watch?v=o4gHCmTQDVI",
  },
  {
    id: 14,
    name: "The Lion King",
    description: "A young lion prince learns his destiny.",
    year: 1994,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    videoUrl: "https://www.youtube.com/watch?v=4sj1MT05lAA",
  },
  {
    id: 15,
    name: "Whiplash",
    description: "A drummer pushed to the limit by his teacher.",
    year: 2014,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w600_and_h900_face/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    videoUrl: "https://www.youtube.com/watch?v=7d_jQycdQGo",
  },
  {
    id: 16,
    name: "Joker",
    description: "A failed comedian descends into madness.",
    year: 2019,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    videoUrl: "https://www.youtube.com/watch?v=zAGVQLHvwOY",
  },
  {
    id: 17,
    name: "Parasite",
    description: "A poor family infiltrates a wealthy household.",
    year: 2019,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    videoUrl: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
  },
  {
    id: 18,
    name: "The Departed",
    description: "An undercover cop and a mole try to expose each other.",
    year: 2006,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
    videoUrl: "https://www.youtube.com/watch?v=iojhqm0JTW4",
  },
  {
    id: 19,
    name: "Django Unchained",
    description: "A freed slave sets out to rescue his wife.",
    year: 2012,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
    videoUrl: "https://www.youtube.com/watch?v=0fUCuvNlOCg",
  },
  {
    id: 20,
    name: "Blade Runner 2049",
    description: "A new blade runner uncovers a dangerous secret.",
    year: 2017,
    type: "MOVIE",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    videoUrl: "https://www.youtube.com/watch?v=gCcx85zbxz4",
  },
  {
  id: 21,
  name: "Pulp Fiction",
  description: "Кілька кримінальних історій переплітаються у хаотичному, стильному та іронічному світі Лос-Анджелеса.",
  year: 1994,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
  videoUrl: "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
},
{
  id: 22,
  name: "The Lord of the Rings: The Fellowship of the Ring",
  description: "Юний гобіт вирушає в небезпечну подорож, щоб знищити перстень абсолютної влади.",
  year: 2001,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
  videoUrl: "https://www.youtube.com/watch?v=V75dMMIW2B4",
},
{
  id: 23,
  name: "The Lord of the Rings: The Two Towers",
  description: "Братство розпадається, а війна за Середземʼя набирає обертів.",
  year: 2002,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
  videoUrl: "https://www.youtube.com/watch?v=LbfMDwc4azU",
},
{
  id: 24,
  name: "The Lord of the Rings: The Return of the King",
  description: "Фінальна битва добра і зла вирішить долю всього Середземʼя.",
  year: 2003,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
  videoUrl: "https://www.youtube.com/watch?v=r5X-hFf6Bwo",
},
{
  id: 25,
  name: "The Silence of the Lambs",
  description: "Молода агентка ФБР звертається по допомогу до небезпечного серійного вбивці.",
  year: 1991,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
  videoUrl: "https://www.youtube.com/watch?v=W6Mm8Sbe__o",
},
{
  id: 26,
  name: "The Wolf of Wall Street",
  description: "Злет і падіння біржового брокера у світі грошей, жадібності та безкарності.",
  year: 2013,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/34m2tygAYBGqA9MXKhRDtzYd4MR.jpg",
  videoUrl: "https://www.youtube.com/watch?v=iszwuX1AK6A",
},
{
  id: 27,
  name: "Inglourious Basterds",
  description: "Альтернативна історія Другої світової, де помста стає мистецтвом.",
  year: 2009,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
  videoUrl: "https://www.youtube.com/watch?v=KnrRy6kSFF0",
},
{
  id: 28,
  name: "The Truman Show",
  description: "Чоловік поступово усвідомлює, що все його життя — це телевізійне шоу.",
  year: 1998,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
  videoUrl: "https://www.youtube.com/watch?v=dlnmQbPGuls",
},
{
  id: 29,
  name: "Goodfellas",
  description: "Історія злету та падіння гангстера у мафіозному світі Нью-Йорка.",
  year: 1990,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
  videoUrl: "https://www.youtube.com/watch?v=qo5jJpHtI1Y",
},
{
  id: 30,
  name: "The Social Network",
  description: "Створення Facebook і конфлікти, які зʼявляються разом із успіхом.",
  year: 2010,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
  videoUrl: "https://www.youtube.com/watch?v=lB95KLmpLR4",
},
{
  id: 31,
  name: "The Pianist",
  description: "Музикант виживає у зруйнованій війною Варшаві під час Голокосту.",
  year: 2002,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
  videoUrl: "https://www.youtube.com/watch?v=BFwGqLa_oAo",
},
{
  id: 32,
  name: "The Imitation Game",
  description: "Геніальний математик намагається зламати код нацистів під час Другої світової.",
  year: 2014,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/zSqJ1qFq8NXFfi7JeIYMlzyR0dx.jpg",
  videoUrl: "https://www.youtube.com/watch?v=nuPZUUED5uk",
},
{
  id: 33,
  name: "Mad Max: Fury Road",
  description: "Безумна гонитва у постапокаліптичному світі заради свободи.",
  year: 2015,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
  videoUrl: "https://www.youtube.com/watch?v=hEJnMQG9ev8",
},
{
  id: 34,
  name: "La La Land",
  description: "Історія кохання, мрій і вибору між почуттями та амбіціями.",
  year: 2016,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
  videoUrl: "https://www.youtube.com/watch?v=0pdqf4P9MB8",
},
{
  id: 35,
  name: "Her",
  description: "Чоловік закохується в операційну систему з власною свідомістю.",
  year: 2013,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg",
  videoUrl: "https://www.youtube.com/watch?v=ne6p6MfLBxc",
},
{
  id: 36,
  name: "Shutter Island",
  description: "Розслідування на закритому острові перетворюється на психологічний кошмар.",
  year: 2010,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/kve20tXwUZpu4GUX8l6X7Z4jmL6.jpg",
  videoUrl: "https://www.youtube.com/watch?v=5iaYLCiq5RM",
},
{
  id: 37,
  name: "No Country for Old Men",
  description: "Випадкова знахідка грошей запускає смертельну гру без правил.",
  year: 2007,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/6o0HTG0Vw1NAYy24y6jH9G01lZt.jpg",
  videoUrl: "https://www.youtube.com/watch?v=38A__WT3-o0",
},
{
  id: 38,
  name: "Black Swan",
  description: "Балерина поступово втрачає межу між реальністю і безумством.",
  year: 2010,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/rH19qEw4j3H8zqE7W9G1Jz0xKcI.jpg",
  videoUrl: "https://www.youtube.com/watch?v=5jaI1XOB-bs",
},
{
  id: 39,
  name: "Arrival",
  description: "Лінгвістка намагається зрозуміти мову прибульців і змінює уявлення про час.",
  year: 2016,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
  videoUrl: "https://www.youtube.com/watch?v=tFMo3UJ4B4g",
},
{
  id: 40,
  name: "Logan",
  description: "Втомлений супергерой захищає дівчинку з надзвичайними здібностями.",
  year: 2017,
  type: "MOVIE",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
  videoUrl: "https://www.youtube.com/watch?v=Div0iP65aZo",
}
];

export const DB_SERIES_IMITATE = [
  {
    id: 101,
    name: "Breaking Bad",
    description: "Вчитель хімії стає виробником метамфетаміну, щоб врятувати сімʼю – і себе.",
    year: 2008,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/3xnWaLQjelJDDF7LT1WBo6f4BRe.jpg",
    videoUrl: "https://www.youtube.com/watch?v=HhesaQXLuRY",
  },
  {
    id: 102,
    name: "Game of Thrones",
    description: "Війна за трон – інтриги, дракони, кров і клятви, які ламають долі.",
    year: 2011,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
    videoUrl: "https://www.youtube.com/watch?v=KPLWWIOCOOQ",
  },
  {
    id: 103,
    name: "Stranger Things",
    description: "Зникнення хлопчика відкриває двері у темну реальність – і секрети містечка.",
    year: 2016,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    videoUrl: "https://www.youtube.com/watch?v=b9EkMc79ZSU",
  },
  {
    id: 104,
    name: "The Witcher",
    description: "Мисливець на монстрів, відьма і принцеса – три долі, що зіштовхнуться в хаосі.",
    year: 2019,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg",
    videoUrl: "https://www.youtube.com/watch?v=ndl1W4ltcmg",
  },
  {
    id: 105,
    name: "Chernobyl",
    description: "Катастрофа, яка змінила світ – і правда, яку намагались поховати.",
    year: 2019,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
    videoUrl: "https://www.youtube.com/watch?v=s9APLXM9Ei8",
  },
  {
    id: 106,
    name: "The Boys",
    description: "Супергерої – не завжди герої. Група людей кидає виклик корпорації та ідолам.",
    year: 2019,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/stTEycfG9928HYGEISBFaG1ngjM.jpg",
    videoUrl: "https://www.youtube.com/watch?v=06rueu_fh30",
  },
  {
    id: 107,
    name: "The Mandalorian",
    description: "Самотній мисливець за головами отримує місію, яка змінить його кодекс назавжди.",
    year: 2019,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
    videoUrl: "https://www.youtube.com/watch?v=aOC8E8z_ifw",
  },
  {
    id: 108,
    name: "Peaky Blinders",
    description: "Британські вулиці, гангстери і сімʼя, яка будує імперію – будь-якою ціною.",
    year: 2013,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/bGZn5RVzMMXju4ev7xbl1aLdXqq.jpg",
    videoUrl: "https://www.youtube.com/watch?v=oVzVdvGIC7U",
  },
  {
    id: 109,
    name: "The Last of Us",
    description: "Після катастрофи двоє людей йдуть крізь країну – де надія дорожча за життя.",
    year: 2023,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    videoUrl: "https://www.youtube.com/watch?v=uLtkt8BonwM",
  },
  {
    id: 110,
    name: "Sherlock",
    description: "Геній дедукції і його напарник – найгостріші справи Лондона в сучасному стилі.",
    year: 2010,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/7WTsnHkbA0FaG6R9twfFde0I9hl.jpg",
    videoUrl: "https://www.youtube.com/watch?v=IrBKwzL3K7s",
  },
  {
    id: 111,
    name: "House of the Dragon",
    description: "Дім драконів розколюється – і війна за спадщину стає неминучою.",
    year: 2022,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
    videoUrl: "https://www.youtube.com/watch?v=DotnJ7tTA34",
  },
  {
    id: 112,
    name: "Better Call Saul",
    description: "Як адвокат Джиммі Макґілл став Солом – і чому це було не випадково.",
    year: 2015,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg",
    videoUrl: "https://www.youtube.com/watch?v=HN4oydykJFc",
  },
  {
    id: 113,
    name: "Narcos",
    description: "Історія наркокартелів, влади і війни, де немає чистих рук.",
    year: 2015,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/rTmal9fDbwh5F0waol2hq35U4ah.jpg",
    videoUrl: "https://www.youtube.com/watch?v=xl8zdCY-abw",
  },
  {
    id: 114,
    name: "Dark",
    description: "Зникнення дітей запускає часовий лабіринт – і ламає логіку реальності.",
    year: 2017,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
    videoUrl: "https://www.youtube.com/watch?v=rrwycJ08PSA",
  },
  {
    id: 115,
    name: "Money Heist",
    description: "Пограбування століття – план, маски і команда, що грає проти системи.",
    year: 2017,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
    videoUrl: "https://www.youtube.com/watch?v=_InqQJRqGW4",
  },
  {
    id: 116,
    name: "Black Mirror",
    description: "Кожна серія – окрема історія про технології, які занадто близько підійшли до нас.",
    year: 2011,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/7PRddO7z7mcPi21nZTCMGShAyy1.jpg",
    videoUrl: "https://www.youtube.com/watch?v=jDiYGjp5iFg",
  },
  {
    id: 117,
    name: "The Office (US)",
    description: "Офісні будні, абсурд і тепло – серіал, який дивишся як комфорт-їжу.",
    year: 2005,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg",
    videoUrl: "https://www.youtube.com/watch?v=tNcDHWpselE",
  },
  {
    id: 118,
    name: "Vikings",
    description: "Сага про Рагнара – битви, амбіції та ціна слави.",
    year: 2013,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg",
    videoUrl: "https://www.youtube.com/watch?v=9GgxinPwAGc",
  },
  {
    id: 119,
    name: "The Crown",
    description: "Корона – це не прикраса. Це тягар, який змінює життя назавжди.",
    year: 2016,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/1M876KPjulVwppEpldhdc8V4o68.jpg",
    videoUrl: "https://www.youtube.com/watch?v=JWtnJjn6ng0",
  },
  {
    id: 120,
    name: "True Detective",
    description: "Похмурі розслідування і психологічна напруга – коли справа стає прокляттям.",
    year: 2014,
    type: "SERIES",
    cast: [],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYjgwYzA1NWMtNDYyZi00ZGQyLWI5NTktMDYwZjE2OTIwZWEwXkEyXkFqcGc@._V1_FMjpg_UX736_.jpg",
    videoUrl: "https://www.youtube.com/watch?v=fVQUcaO4AvE",
  },
  {
    id: 121,
    name: "Westworld",
    description: "Парк майбутнього, де андроїди починають усвідомлювати себе – і ламати правила.",
    year: 2016,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/8MfgyFHf7XEboZJPZXCIDqqiz6e.jpg",
    videoUrl: "https://www.youtube.com/watch?v=IuS5huqOND4",
},
{
    id: 122,
    name: "Dexter",
    description: "Судмедексперт вдень і серійний вбивця вночі – з власним кодексом.",
    year: 2006,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/q8dWfc4JwQuv3HayIZeO84jAXED.jpg",
    videoUrl: "https://www.youtube.com/watch?v=YQeUmSD1c3g",
},
{
    id: 123,
    name: "Lost",
    description: "Авіакатастрофа, загадковий острів і таємниці, які змінюють всіх.",
    year: 2004,
    type: "SERIES",
    cast: [],
    posterUrl: "https://image.tmdb.org/t/p/w500/ogK9wOT6d3xNQz4qz9v2Y6pQd5x.jpg",
    videoUrl: "https://www.youtube.com/watch?v=KTu8iDynwNc",
  },
{
  id: 124,
  name: "The Sopranos",
  description: "Мафтозний бос балансує між криміналом і сімейною терапією.",
  year: 1999,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/6oGv7zUj9Xu3c5P6OZkG5H1kLz2.jpg",
  videoUrl: "https://www.youtube.com/watch?v=KMx4iFcozK0",
},
{
  id: 125,
  name: "Fargo",
  description: "Злочини у маленьких містах – де випадковість запускає хаос.",
  year: 2014,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/9ZJ0X6sJv6wXyK4p9l5dZ8FJpG8.jpg",
  videoUrl: "https://www.youtube.com/watch?v=SetgvHG3w48",
},
{
  id: 126,
  name: "Mindhunter",
  description: "Початок профайлінгу серійних вбивць у ФБР.",
  year: 2017,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/6G2n1mP7xQy5L1z5wH8QK5xE6pG.jpg",
  videoUrl: "https://www.youtube.com/watch?v=DHJO6VR6TYY",
},
{
  id: 127,
  name: "The Walking Dead",
  description: "Світ після зомбі-апокаліпсису – і справжні монстри серед людей.",
  year: 2010,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/rqeYMLryjcawh2JeRpCVUDXYM5b.jpg",
  videoUrl: "https://www.youtube.com/watch?v=sfAc2U20uyg",
},
{
  id: 128,
  name: "Better Call Saul",
  description: "Історія становлення одного з найхаризматичніших адвокатів телевізії.",
  year: 2015,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg",
  videoUrl: "https://www.youtube.com/watch?v=HN4oydykJFc",
},
{
  id: 129,
  name: "Ozark",
  description: "Фінансист занурюється у кримінальний світ, щоб врятувати родину.",
  year: 2017,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/4q2NNj4S5dG2R3p7nKZ6W1R7Xz.jpg",
  videoUrl: "https://www.youtube.com/watch?v=5hAXVqrljbs",
},
{
  id: 130,
  name: "Euphoria",
  description: "Підлітки, залежності і пошук себе у світі без фільтрів.",
  year: 2019,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/3Q0hd3heuWwDWpwcDkhQOA6TYWI.jpg",
  videoUrl: "https://www.youtube.com/watch?v=UR4Pxgnm-GA",
},
{
  id: 131,
  name: "House",
  description: "Геній діагностики, який рятує життя, порушуючи всі правила.",
  year: 2004,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/lp2sA1xMZ0D1C8cUqJ8Yy1kN6vN.jpg",
  videoUrl: "https://www.youtube.com/watch?v=MczMB8nU1sY",
},
{
  id: 132,
  name: "Suits",
  description: "Юристи, амбіції і великі ставки у Нью-Йорку.",
  year: 2011,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/6UeRkQO1J3o8wF6B4E1y0pE4WfC.jpg",
  videoUrl: "https://www.youtube.com/watch?v=Ab2YIbP5xwM",
},
{
  id: 133,
  name: "How I Met Your Mother",
  description: "Історія дружби, кохання і пошуків “тієї самої”.",
  year: 2005,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/b34jPzmB0wZy7T9z7D1Y4x1ZJ1A.jpg",
  videoUrl: "https://www.youtube.com/watch?v=k4z0k_J8Vkk",
},
{
  id: 134,
  name: "The Big Bang Theory",
  description: "Гіки, наука і гумор – коли формули зустрічають життя.",
  year: 2007,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/ooBGRQBdbGzBxAVfExiO8r7kloA.jpg",
  videoUrl: "https://www.youtube.com/watch?v=WBb3fojgW0Q",
},
{
  id: 135,
  name: "Prison Break",
  description: "Втеча з в'язниці як ідеально прорахований план.",
  year: 2005,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/5E1BhkCgjLBlqx557Z5yzcN0i88.jpg",
  videoUrl: "https://www.youtube.com/watch?v=AL9zLctDJaU",
},
{
  id: 136,
  name: "Mr. Robot",
  description: "Хакер, змови і боротьба з системою – всередині власної свідомості.",
  year: 2015,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/oKIBhzZzDX07SoE2bOLhq2EE8rf.jpg",
  videoUrl: "https://www.youtube.com/watch?v=N6HGuJC--rk",
},
{
  id: 137,
  name: "The Handmaid’s Tale",
  description: "Антиутопія про контроль, страх і боротьбу за свободу.",
  year: 2017,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/oIkxqt6ug5zT5ZSUUyc1Iqopf02.jpg",
  videoUrl: "https://www.youtube.com/watch?v=dVLiDETfx1c",
},
{
  id: 138,
  name: "Loki",
  description: "Бог хитрощів у пастці часу і альтернативних реальностей.",
  year: 2021,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
  videoUrl: "https://www.youtube.com/watch?v=nW948Va-l10",
},
{
  id: 139,
  name: "Wednesday",
  description: "Темний гумор, детектив і харизма Венздей Аддамс.",
  year: 2022,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
  videoUrl: "https://www.youtube.com/watch?v=Di310WS8zLk",
},
{
  id: 140,
  name: "Arcane",
  description: "Анімаційний серіал про конфлікт міст, технології і долі.",
  year: 2021,
  type: "SERIES",
  cast: [],
  posterUrl: "https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
  videoUrl: "https://www.youtube.com/watch?v=fXmAurh012s",
}
];


